# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  maven/test:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Generate cache seed
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
      - restore_cache:
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          name: Install Dependencies
          command: mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline
      - run:
          name: Run Tests
          command: mvn verify
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - store_test_results:
          path: target/surefire-reports

workflows:
  test:
    jobs:
      - maven/test
